name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - working-directory: mobile
        run: npm install
      - uses: reactivecodes/easy-android-ebook-build-action@v1
        with:
          api-path: mobile/app.json
          project-path: mobile
          android-path: android
      - uses: andresaravi/actions-expo-eas-update@v1
        with:
          eas-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          expo-account-name: ${{ secrets.EXPO_ACCOUNT_NAME }}
          expo-token: ${{ secrets.EXPO_ACCESS_TOKEN }}
          message: 'Automated EAS Update'
          channel: production
          native-distribution: 'apk'
        working-directory: mobile

  deploy-admin:
    runs-on: ubuntu-latest
    needs: build-mobile
    steps:
      - uses: actions/checkout@v4
      - uses actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - working-directory: admin
        run: npm install
      - working-directory: admin
        run: npm run build
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: admin
          scope: ${{ secrets.VERCEL_SCOPE }}
